### ISSUE TITLE
Bug: 'KNeighborsAlgorithm' object has no attribute 'classes_'

### ISSUE THREAD

**Issue by strukevych** [mljar/mljar-supervised#669] opened 2023-11-03 20:58 UTC
Current behavior:
'KNeighborsAlgorithm' object has no attribute 'classes_'
Problem during computing permutation importance. Skipping ...

Expected: KNeighbors to be trained

**Comment by pplonski** [comment] 2023-11-07 08:35
Which version are you using?

**Comment by strukevych** [comment] 2023-11-08 00:19
Python 3.11
mljar 1.1.1

**Comment by pplonski** [comment] 2023-11-08 09:42
Thanks @strukevych, looks like it is some bug. PR are welcome!

**Comment by Hk669** [comment] 2023-11-30 10:07
hey @pplonski ,  i am keen on contributing and would like to gather more information to better understand the problem and work towards a resolution.

**Comment by Hk669** [comment] 2023-11-30 11:59
@pplonski , made a PR #679 . 
i think this will solve the issue for the _classes attribute in the KNieghborsAlgorithm

**Comment by pplonski** [comment] 2023-12-01 11:23
Thank you @Hk669, I've added comments to PR.

**Comment by pplonski** [comment] 2024-09-30 11:23
@Marchlak are we able to reproduce the issue, or it was fixed with 1.5 scikit-learn?

**Comment by Marchlak** [comment] 2024-09-30 13:38
@pplonski I haven't encountered this problem

**Closed** 2024-09-30 13:39 UTC
Labels: bug, help wanted, good first issue
