### ISSUE TITLE
mljar is crashing on titanic data

### ISSUE THREAD

**Issue by yairVanti** [mljar/mljar-supervised#546] opened 2022-06-02 15:07 UTC
mljar version : 0.11.2
python 3.8 on macOS
log :
1_Linear average_precision 0.812127 trained in 15.46 seconds (1-sample predict time 0.0346 seconds)
* Step default_algorithms will try to check up to 5 models

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

report dump :
Crashed Thread:        11

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000020
Exception Codes:       0x0000000000000001, 0x0000000000000020
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [55564]

dataset from [https://www.kaggle.com/c/titanic/data](url)

**Comment by pplonski** [comment] 2022-06-02 15:13
thanks @yairVanti for reporting the issue, what hardware do you have? what is OS version?

**Comment by pplonski** [comment] 2023-05-01 13:31
I'm closing the issue, I cant reproduce it. If you still have problems, please reopen.

Have a nice day!

**Closed by pplonski** 2023-05-01 13:31 UTC
