### ISSUE TITLE
about mode='Optuna'

### ISSUE THREAD

**Issue by xuzhang5788** [mljar/mljar-supervised#366] opened 2021-04-02 18:46 UTC
even I installed it with @dev, I still can not use this option. Any suggestions?

**Comment by pplonski** [comment] 2021-04-03 11:33
@xuzhang5788 I've updated the PyPi and `master` branches. You can use them.

To run in the Optuna mode:

```python
automl = AutoML(
    algorithms=["Xgboost", "LightGBM", "CatBoost", "Random Forest", "Extra Trees", "Neural Networks"],
    mode="Optuna",
    optuna_time_budget=1200,
    total_time_limit=24*3600
)
automl.fit(X, y)
```

The `optuna_time_budget=1200` means that 20 minutes will be used by Optuna to tune each algorithm. If there are 6 types of algorithms, then Optuna will use 6*20=120 minutes for all tuning. Then, the  `total_time_limit=24*3600` will be used for ML training (after tuning). In the Optuna mode, the tuning time and training time are separate.

The Optuna is not using feature engineering. To enable feature engineering:


```python
automl = AutoML(
    algorithms=["Xgboost", "LightGBM", "CatBoost", "Random Forest", "Extra Trees", "Neural Networks"],
    mode="Optuna",
    optuna_time_budget=1200,
    total_time_limit=24*3600,
    kmeans_features=True,
    golden_features=True,
    mix_encoding=True,
    features_selection=True
)
automl.fit(X, y)
```

The example of Optuna mode on Kaggle TPS Apr-21 data: https://www.kaggle.com/mt77pp/mljar-automl-tps-apr-2021-manual-features



@xuzhang5788 please let me know if it works for you.

**Comment by xuzhang5788** [comment] 2021-04-03 17:41
Sorry, it doesn't work with an error, TypeError: __init__() got an unexpected keyword argument 'optuna_time_budget'

**Comment by pplonski** [comment] 2021-04-03 18:10
Please try to install the package in a fresh environment. It should work. When I install it in Kaggle kernel it is working.

**Comment by xuzhang5788** [comment] 2021-04-04 06:48
Sorry. I reinstalled the package. When running cell 'from supervised.automl import AutoML', I got

RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

I reran that cell, errors disappeared, I ran 

automl = AutoML(
    algorithms=["Xgboost", "LightGBM", "CatBoost"],
    mode="Optuna",
    eval_metric='mse',
    optuna_time_budget=1200,
    total_time_limit=24*3600,
    kmeans_features=True,
    golden_features=True,
    mix_encoding=True,
    features_selection=True
)
automl.fit(X_train, y_train)

I got 

AutoML directory: AutoML_13
Expected computing time:
Total training time: Optuna + ML training = 90000 seconds
Total Optuna time: len(algorithms) * optuna_time_budget = 3600 seconds
Total ML model training time: 86400 seconds
The task is regression with evaluation metric mse
AutoML will use algorithms: ['Xgboost', 'LightGBM', 'CatBoost']
AutoML will stack models
AutoML will ensemble availabe models

2021-04-03 23:31:54,586 supervised.exceptions ERROR No models produced. 
Please check your data or submit a Github issue at https://github.com/mljar/mljar-supervised/issues/new.

AutoML steps: ['simple_algorithms', 'default_algorithms', 'insert_random_feature', 'features_selection', 'boost_on_errors', 'ensemble', 'stack', 'ensemble_stacked']
Skip simple_algorithms because no parameters were generated.
Skip default_algorithms because no parameters were generated.
Skip insert_random_feature because no parameters were generated.
Skip features_selection because no parameters were generated.
Skip boost_on_errors because no parameters were generated.

 AutoMLException: No models produced. 
Please check your data or submit a Github issue at https://github.com/mljar/mljar-supervised/issues/new.

Before my data was okay for other modes.

**Comment by pplonski** [comment] 2021-04-06 08:39
@xuzhang5788 you are using Optuna mode correctly. There must be other bug or problem.

Could you please install the latest release code:

```
pip install -U mljar-supervised
```

and check how it runs with `Compete` and `Optuna` modes?

**Comment by xuzhang5788** [comment] 2021-04-06 18:53
Sorry. It still doesn't work. 
conda env with python 3.9.0, ubuntu 20.04

**Comment by pplonski** [comment] 2021-04-06 19:20
@xuzhang5788 from your previous massages, it looks that MLJAR AutoML is running but can't analyze your data. It produces some errors. Could you please post the code example with data?

**Comment by xuzhang5788** [comment] 2021-04-06 20:51
Now, I have the following error when setting automal: 
__init__() got an unexpected keyword argument 'optuna_time_budget'

**Comment by xuzhang5788** [comment] 2021-04-06 23:19
My data is like 
X_train
  | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | ... | 1014 | 1015 | 1016 | 1017 | 1018 | 1019 | 1020 | 1021 | 1022 | 1023
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
K | V | L | G | S | G | A | F | G | T | ... | 0 | 0 | 1 | 1 | 0 | 1 | 0 | 1 | 1 | 0
K | P | L | G | E | G | A | F | G | Q | ... | 0 | 0 | 0 | 1 | 1 | 0 | 0 | 1 | 0 | 0
E | F | L | G | R | G | A | F | G | Q | ... | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 1
R | V | L | G | K | G | G | Y | G | K | ... | 0 | 0 | 0 | 1 | 1 | 0 | 0 | 0 | 0 | 0
N | A | I | I | D | D | Y | K | V | K | ... | 1 | 1 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0
... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ...
R | V | L | G | K | G | G | Y | G | K | ... | 1 | 0 | 0 | 0 | 1 | 0 | 1 | 1 | 0 | 1
R | K | L | G | W | G | H | F | S | T | ... | 0 | 1 | 1 | 1 | 0 | 0 | 0 | 0 | 0 | 0
K | V | L | G | S | G | A | F | G | K | ... | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
K | V | L | G | S | G | A | F | G | T | ... | 1 | 1 | 1 | 0 | 0 | 0 | 0 | 0 | 1 | 0
K | T | L | G | E | G | E | F | G | K | ... | 1 | 1 | 1 | 0 | 1 | 0 | 0 | 1 | 1 | 0

77312 rows × 1109 columns
from column[:85] are categorical variables, column[85:-1] are numerical variables only use 0 or 1. y_train is a numerical variable.
from supervised.automl import AutoML

automl = AutoML(ml_task='regression',
    algorithms=["Xgboost", "LightGBM", "CatBoost"],
    mode="Optuna",
    eval_metric='mse',
    optuna_time_budget=1200,
    total_time_limit=24*3600,
#    kmeans_features=True,
#    golden_features=True,
#    mix_encoding=True,
#    features_selection=True
               )
automl.fit(X_train, y_train)

I got
AutoML directory: AutoML_21
Expected computing time:
Total training time: Optuna + ML training = 90000 seconds
Total Optuna time: len(algorithms) * optuna_time_budget = 3600 seconds
Total ML model training time: 86400 seconds
The task is regression with evaluation metric mse
AutoML will use algorithms: ['Xgboost', 'LightGBM', 'CatBoost']
AutoML will stack models
AutoML will ensemble availabe models

2021-04-06 16:11:39,285 supervised.exceptions ERROR No models produced. 
Please check your data or submit a Github issue at https://github.com/mljar/mljar-supervised/issues/new.

AutoML steps: ['simple_algorithms', 'default_algorithms', 'boost_on_errors', 'ensemble', 'stack', 'ensemble_stacked']
Skip simple_algorithms because no parameters were generated.
Skip default_algorithms because no parameters were generated.
Skip boost_on_errors because no parameters were generated.

 AutoMLException: No models produced. 
Please check your data or submit a Github issue at https://github.com/mljar/mljar-supervised/issues/new. 

If I use mode='Compete', it worked well

**Comment by pplonski** [comment] 2021-04-07 15:27
@xuzhang5788 is your data publicly available? So I can run locally? Could you please send me link to data? Or send data or some sample?

Do you get good models with Compete?

**Comment by xuzhang5788** [comment] 2021-04-07 16:03
@pplonski Thank you.
My data is not publicly available, but I can give you. Please give me your email address or tell me how to send it to you.

**Comment by xuzhang5788** [comment] 2021-04-07 16:05
@pplonski 
Yes, I think I got good models with Compete mode.

**Comment by pplonski** [comment] 2021-04-07 17:39
@xuzhang5788 please send data and code to piotr@mljar.com

**Comment by pplonski** [comment] 2021-04-08 11:17
@xuzhang5788 I found the issue. The `mse` metric was missing in the Optuna tuner code.

Additionally, looks like Xgboost and CatBoost support only `rmse`. I will add them.

**Comment by pplonski** [comment] 2021-04-08 14:21
@xuzhang5788 it should be fixed now. Please install the package directly from GitHub:

```
pip install -q -U git+https://github.com/mljar/mljar-supervised.git@master
```

**Comment by xuzhang5788** [comment] 2021-04-08 21:59
Thank you! It works now.
Is the Optuna mode always better than the Compete mode? I am a little bit confused about how to choose the mode.

**Comment by pplonski** [comment] 2021-04-09 06:45
@xuzhang5788 great. 

### `Optuna` vs. `Compete` 

It depends on your dataset. Sometimes `Compete` works, because you will have a lot of models which will work great when ensembling and stacking. Sometimes you need a highly tuned model to score well, then `Optuna` should be used.

You can try to use both and ensemble them? (Never tried that, but maybe will work)

**Closed by pplonski** 2021-04-09 06:45 UTC
Labels: bug

**Comment by xuzhang5788** [comment] 2021-04-09 20:07
I tried Optuna mode, but I got 'kernel dead' after optuna searching finished. I tried twice, I got the same 'kernel dead' at the same location. It looks like it can do Optuna, but can't continue to do ML training.

**Comment by pplonski** [comment] 2021-04-09 20:18
Could you please provide code and data to reproduce?

pt., 9 kwi 2021, 22:08 użytkownik xuzhang5788 ***@***.***>
napisał:

**Comment by prateekchandrajha** [comment] 2021-11-04 13:21
> @xuzhang5788 it should be fixed now. Please install the package directly from GitHub:
> 
> ```
> pip install -q -U git+https://github.com/mljar/mljar-supervised.git@master
> ```

This happens when I run it in Sagemaker 

ERROR: Could not find a version that satisfies the requirement pandas>=1.2.0 (from mljar-supervised)
ERROR: No matching distribution found for pandas>=1.2.0

**Comment by pplonski** [comment] 2021-11-04 13:34
Would you please install package without `-q` flag and paste the output? Thank you

**Comment by apprenticemanxxx** [comment] 2022-11-01 21:37
Could I define my own `eval_metric` in the `Optuna` mode?

**Comment by pplonski** [comment] 2022-11-02 07:54
Yes, you can use custom evaluation metric in `Optuna` mode. Please check example code on how to define custom evaluation metric here: https://github.com/mljar/mljar-supervised/issues/390#issuecomment-830049603

**Comment by apprenticemanxxx** [comment] 2022-11-02 18:43
> 

I tried but it always raise the error:
```
Optuna optimizes LightGBM with time budget 330 seconds eval_metric user_defined_metric (minimize)
[W 2022-11-02 18:41:24,718] Trial 0 failed, because the value None could not be cast to float.
Exception in LightgbmObjective 0
[W 2022-11-02 18:41:33,346] Trial 1 failed, because the value None could not be cast to float.
Exception in LightgbmObjective 0
```

**Comment by pplonski** [comment] 2022-11-02 18:47
Could you please provide code sample?

**Comment by apprenticemanxxx** [comment] 2022-11-03 00:49
Hi @pplonski ,

The idea of my `eval_metric` is that I would like to minimize the ratio of predicted points having `mape` greater than 0.2
And here's the code that I leverage the `mean_absolute_percentage_error` from `sklearn`:
```
def custom_mape(actual_value, pred_value, sample_weight=None):
  result = [mean_absolute_percentage_error([actual_value[inx]], [pred_value[inx]], sample_weight=None) 
                                            for inx in range(len(pred_value))] 
  score = sum(map(lambda mape: mape > 0.2, result))/len(pred_value)
  return score
  ```
  And this is the code without using `mean_absolute_percentage_error`:
  ```
 def custom_mape(actual_value, pred_value, sample_weight=None):
  result = [abs(actual_value[inx] - pred_value[inx])/actual_value[inx] for inx in range(len(pred_value))] 
  filtered = filter(lambda mape: mape > 0.2, result)
  score = 100*len(list(filtered))/len(pred_value) 
  return score
  ```
  
  And both of them give me errors. Could you help me on that. Thank you.

**Comment by pplonski** [comment] 2022-11-04 08:46
Hi @apprenticemanxxx,

I recommend:

1. save arguments to a file in the custom function, 
2. call AutoML with custom metric and save values into a file,
3. load values in Jupyter Notebook and try to debug locally and understand the problem.

```python
def custom_mape(actual_value, pred_value, sample_weight=None):
  # save values to file
  actual_value.to_csv('actual_value.csv')
  pred_value.to_csv('pred_value.csv')
  # old function
  result = [mean_absolute_percentage_error([actual_value[inx]], [pred_value[inx]], sample_weight=None) 
                                            for inx in range(len(pred_value))] 
  score = sum(map(lambda mape: mape > 0.2, result))/len(pred_value)
  return score
```
