### ISSUE TITLE
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

### ISSUE THREAD

**Issue by ijeffking** [mljar/mljar-supervised#279] opened 2021-01-09 18:27 UTC
could not convert string to float: "This story is about a canoe float with grandpa. We had a great float trip with my dad but were saddened to realize how bad his Alzheimer's really is."

**Comment by pplonski** [comment] 2021-01-10 00:30
Thank you for reporting the issue. Could you please provide the code example to reproduce the problem. Maybe there is some problem with column type in the input data frame? Is the column with text set as `object` type?

**Comment by ijeffking** [comment] 2021-01-10 06:14
Appreciate the response. This is the dataset https://raw.githubusercontent.com/dphi-official/Datasets/master/hippocorpus/train_set_label.csv

Yes the column with text is set as object type.

**Comment by pplonski** [comment] 2021-01-11 22:25
@ijeffking How are you loading the date into the pandas? I have checked the dataset from your comment and it doesn't keep all columns aligned in the Excel preview, which means that there can be problems with separator or column number problem in the data.

**Comment by pplonski** [comment] 2021-01-12 19:13
OK, I got the reason. Some of the values in the data are larger than float32 range.

**Comment by pplonski** [comment] 2021-01-12 20:39
I clipped data to be in the `float32` range. Fix will be in the next release `0.7.20`.

**Closed by pplonski** 2021-01-12 20:39 UTC
Labels: bug

**Comment by ijeffking** [comment] 2021-01-12 21:59
Thank you so much
