### ISSUE TITLE
Error for 1_Baseline

### ISSUE THREAD

**Issue by TZ-2018** [mljar/mljar-supervised#331] opened 2021-03-07 21:29 UTC
## Error for 1_Baseline

Found input variables with inconsistent numbers of samples: [1032, 172]
Traceback (most recent call last):
  File "E:\Anaconda\envs\mljar\lib\site-packages\supervised\base_automl.py", line 1046, in _fit
    trained = self.train_model(params)
  File "E:\Anaconda\envs\mljar\lib\site-packages\supervised\base_automl.py", line 354, in train_model
    mf.train(results_path, model_subpath)
  File "E:\Anaconda\envs\mljar\lib\site-packages\supervised\model_framework.py", line 128, in train
    train_data, validation_data = self.validation.get_split(k_fold, repeat)
  File "E:\Anaconda\envs\mljar\lib\site-packages\supervised\validation\validation_step.py", line 36, in get_split
    return self.validator.get_split(k, repeat)
  File "E:\Anaconda\envs\mljar\lib\site-packages\supervised\validation\validator_split.py", line 83, in get_split
    random_state=self.random_seed + repeat,
  File "E:\Anaconda\envs\mljar\lib\site-packages\sklearn\model_selection\_split.py", line 2172, in train_test_split
    arrays = indexable(*arrays)
  File "E:\Anaconda\envs\mljar\lib\site-packages\sklearn\utils\validation.py", line 299, in indexable
    check_consistent_length(*result)
  File "E:\Anaconda\envs\mljar\lib\site-packages\sklearn\utils\validation.py", line 263, in check_consistent_length
    " samples: %r" % [int(l) for l in lengths])
ValueError: Found input variables with inconsistent numbers of samples: [1032, 172]

**Comment by pplonski** [comment] 2021-03-08 07:05
@TZ-2018 thank you for reporting the issue. Looks like some problem with training data. Do you check your training data size? Can you please provide a code sample and data example so I can try to reproduce the issue?

**Comment by pplonski** [comment] 2021-03-24 10:40
@TZ-2018 I'm closing the issue as there is no additional info. Looks like there is some problem with input data. If you still have the problem, please reopen the issue with more information.

**Closed by pplonski** 2021-03-24 10:40 UTC
Labels: bug
