### ISSUE TITLE
trained error

### ISSUE THREAD

**Issue by jungjongho** [mljar/mljar-supervised#703] opened 2024-02-03 08:42 UTC
automl = AutoML(
    algorithms=["CatBoost", "Xgboost", "LightGBM"],
    mode="Compete",
    ml_task="multiclass_classification",
    eval_metric='f1',
    random_state=42,
    total_time_limit=14400,
    model_time_limit=None,
)

#모델 학습
automl.fit(df_preprocess, df_y_data_encoded)

df_preprocess => (96294,15)
df_y_data_encoded.distinct() => 0,1,2,3,4,5,6

cannot reshape array of size 606648 into shape (12380,7) Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/supervised/base_automl.py", line 1195, in fit trained = self.train_model(params) File "/usr/local/lib/python3.10/dist-packages/supervised/base_automl.py", line 401, in train_model mf.train(results_path, model_subpath) File "/usr/local/lib/python3.10/dist-packages/supervised/model_framework.py", line 254, in train learner.fit( File "/usr/local/lib/python3.10/dist-packages/supervised/algorithms/lightgbm.py", line 237, in fit self.model = lgb.train( File "/usr/local/lib/python3.10/dist-packages/lightgbm/engine.py", line 282, in train evaluation_result_list.extend(booster.eval_train(feval)) File "/usr/local/lib/python3.10/dist-packages/lightgbm/basic.py", line 3892, in eval_train return self.inner_eval(self._train_data_name, 0, feval) File "/usr/local/lib/python3.10/dist-packages/lightgbm/basic.py", line 4635, in __inner_eval feval_ret = eval_function(self.inner_predict(data_idx), cur_data) File "/usr/local/lib/python3.10/dist-packages/supervised/utils/metric.py", line 214, in lightgbm_eval_metric_f1 preds = np.reshape(preds, (rows, cols), order="F") File "<_array_function internals>", line 180, in reshape File "/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py", line 298, in reshape return _wrapfunc(a, 'reshape', newshape, order=order) File "/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc return bound(args, *kwds) ValueError: cannot reshape array of size 606648 into shape (12380,7)

**Comment by pplonski** [comment] 2024-02-05 08:08
Thank you @jungjongho for reporting. I

**Comment by sumantabasak** [comment] 2024-06-01 11:48
I'm having same issue. @pplonski can you please look into this?

**Comment by pplonski** [comment] 2024-06-03 08:52
Hi @sumantabasak,

thanks for reporting, could you please provide example code to reproduce issue?

**Comment by pplonski** [comment] 2024-09-30 08:13
Closing because no data to reproduce. If you have the same issue, please create a new issue and attach data and code to reproduce issue.

**Closed by pplonski** 2024-09-30 08:13 UTC
