### ISSUE TITLE
Prediction time is taking longer than expected

### ISSUE THREAD

**Issue by salomonMuriel** [mljar/mljar-supervised#312] opened 2021-02-15 17:08 UTC
Hi! I've banged my head against the wall for a couple of days and can't solve this. Prediction times are taking much longer than is to be expected. Running an AutoML model for a regression task takes upwards of 3 seconds for a single prediction.

I believe this is because the predict method for the AutoML class loads every model that was saved every time you ask for a prediction. It would be much more optimal to load all models on call init, and call their prediction methods without having to load them every time.

**Comment by pplonski** [comment] 2021-02-15 17:21
Thank you @salomonMuriel for reporting. Have you used Stacking? I will dig into it.

**Comment by RafaD5** [comment] 2021-02-15 19:39
I think that if you add the attribute self.loaded as False in the BaseAutoML class and that if you change the following lines in the method _base _predict()
```
#old
self._check_is_fitted()
#new
if not self._loaded:
   self._check_is_fitted()
   self._loaded = True
```
the prediction time decreases because the models are only loaded the first time.
I used .predict() two times for the same X and the results are the following
![image](https://user-images.githubusercontent.com/37419841/107987068-6597e700-6f9b-11eb-95ec-14e2cfc95e57.png)

If you want I can put in a PR with the fix

**Comment by pplonski** [comment] 2021-02-15 21:00
Thank you, @RafaD5 good catch! Please give me some time to check if that's the only issue and I will let you know if ready to PR.

Some more questions:
- Is 1 second a prediction time for one sample? Is it acceptable or still too slow?
- How many models are in the AutoML? 
- Do you have feature engineering features enabled (k-means, golden features)? 
- Can you post a minimal code example to reproduce this problem?

**Comment by RafaD5** [comment] 2021-02-15 21:44
I found another fix that can help decrease the first prediction time. I changed the load() method of the BaseAutoML class so that it just loads the neccesary models to predict, not all the trained models:
![image](https://user-images.githubusercontent.com/37419841/107995121-1312f680-6fac-11eb-8d0e-0b082fde287f.png)

I answer you the questions in a few minutes

**Comment by pplonski** [comment] 2021-02-16 11:10
Thank you @RafaD5, I've found one more thing that slows down the prediction time. I'm always loading out-of-folds predictions when loading models. It is needed when the training is interrupted to continue training (oofs are needed for ensemble and stacking). There will 3 steps to speed-up predictions:
- load only needed models
- load only once
- don't load OOF predictions

I'm working on this right now, so the fix should be today/tomorrow.

**Comment by pplonski** [comment] 2021-02-16 20:58
@RafaD5 @salomonMuriel I've pushed fixes to the `dev` branch, to install the package with the newest changes please run:

```bash
pip install -U git+https://github.com/mljar/mljar-supervised.git@dev
```

I checked the solution by running few examples and it was working fine. 

What I did:
- I only load models one time in the `predict()`
- I added lazy loading, so only models needed for computing predictions are loaded from the hard drive - they are loaded during `predict()`. For other models, only parameters are loaded (from *.json files)
- I removed loading out-of-folds predictions

The changes are not backward compatible so there is a need to retrain models from scratch.

**Comment by salomonMuriel** [comment] 2021-02-19 13:10
That's great @pplonski ! Much appreciated. Our work with @RafaD5 and I believe that of many users of the package in production environments is very much affected by response times so every msec counts.

Another possible change would be to pre-load the models needed for prediction on the class init from a pre-trained set of moldes (so basically when a folder path is provided), so that they would be already loaded when .predict() is called. Maybe it could be added as an optional boolean parameter?

**Comment by pplonski** [comment] 2021-02-19 18:52
@salomonMuriel I agree, the parameter to load models can be a way to go, I need to think about how this can be effectively implemented. I will let you know at the beginning of the next week.

**Comment by pplonski** [comment] 2021-02-22 08:34
@salomonMuriel I thought about this and it will be implemented in the following way:
- if the training was interrupted, and AutoML is re-loaded, then lazy loading will be applied
- for AutoML successfully trained, there will be a full load of the best model

**Comment by pplonski** [comment] 2021-02-22 13:08
All code updates are in the `dev` branch. The changes:
- removed `best_model.txt` file, all information about the best model is stored in the `params.json` file
- information about which models should be loaded for computing prediction is stored in the `params.json` file with the key `load_on_predict`. Models are loaded during AutoML initialization. Only models needed to run the best model are loaded. If the training is not finished, then all models are loaded, but with lazy loading.

The changes will to the `0.9.0` release.

**Closed** 2021-02-22 13:08 UTC
Labels: enhancement

**Comment by salomonMuriel** [comment] 2021-02-22 17:22
Amazing @pplonski !! Thanks so much, this is extremely helpful.
