### ISSUE TITLE
Error with golden_features

### ISSUE THREAD

**Issue by toan01-uet** [mljar/mljar-supervised#450] opened 2021-08-06 08:08 UTC
I can't predict target, because the number of features in data(train, test) is not same. Although the number of features in X_train and X_test is same.
The fit method used:
```python
from supervised.automl import AutoML
automl_co = AutoML(mode="Compete", 
                   total_time_limit = 12600, 
                   golden_features=True,
                    features_selection=False,
                    stack_models=True,
                    train_ensemble=True,
                    explain_level=0,
                   results_path='./mljar_co',
                    validation_strategy={
                        "validation_type": "kfold",
                        "k_folds": 5,
                        "shuffle": False,
                        "stratify": True,
    }) 
automl_co.fit(X_train, y_train)
y_pred = automl_co.predict_all(X_test)
```
The error:
```p
LightGBMError: The number of features in data (129) is not the same as it was in training data (130).
```

**Comment by pplonski** [comment] 2021-08-09 06:20
@toan01-uet thank you for reporting. Looks like some bug. I will need code and data to reproduce it.

**Comment by pplonski** [comment] 2021-09-02 11:25
@toan01-uet closing the issue, I cant reproduce it. Please provide input data so I can reproduce the problem.

**Closed by pplonski** 2021-09-02 11:25 UTC
