### ISSUE TITLE
## Error for 3_Optuna_CatBoost

### ISSUE THREAD

**Issue by ijeffking** [mljar/mljar-supervised#402] opened 2021-05-23 15:34 UTC
Bad value for num_feature[non_default_doc_idx=0,feature_idx=9]="Rufiji": Cannot convert 'b'Rufiji'' to float
Traceback (most recent call last):
  File "_catboost.pyx", line 1980, in _catboost.get_float_feature
  File "_catboost.pyx", line 1085, in _catboost._FloatOrNan
  File "_catboost.pyx", line 917, in _catboost._FloatOrNanFromString
TypeError: Cannot convert 'b'Rufiji'' to float

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/supervised/base_automl.py", line 1092, in _fit
    trained = self.train_model(params)
  File "/usr/local/lib/python3.7/dist-packages/supervised/base_automl.py", line 365, in train_model
    mf.train(results_path, model_subpath)
  File "/usr/local/lib/python3.7/dist-packages/supervised/model_framework.py", line 210, in train
    self.learner_params,
  File "/usr/local/lib/python3.7/dist-packages/supervised/tuner/optuna/tuner.py", line 166, in optimize
    self.random_state,
  File "/usr/local/lib/python3.7/dist-packages/supervised/tuner/optuna/catboost.py", line 50, in __init__
    weight=sample_weight_validation,
  File "/usr/local/lib/python3.7/dist-packages/catboost/core.py", line 455, in __init__
    self._init(data, label, cat_features, text_features, embedding_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names, thread_count)
  File "/usr/local/lib/python3.7/dist-packages/catboost/core.py", line 966, in _init
    self._init_pool(data, label, cat_features, text_features, embedding_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names, thread_count)
  File "_catboost.pyx", line 3550, in _catboost._PoolBase._init_pool
  File "_catboost.pyx", line 3597, in _catboost._PoolBase._init_pool
  File "_catboost.pyx", line 3438, in _catboost._PoolBase._init_features_order_layout_pool
  File "_catboost.pyx", line 2477, in _catboost._set_features_order_data_pd_data_frame
  File "_catboost.pyx", line 2021, in _catboost.create_num_factor_data
  File "_catboost.pyx", line 1982, in _catboost.get_float_feature
_catboost.CatBoostError: Bad value for num_feature[non_default_doc_idx=0,feature_idx=9]="Rufiji": Cannot convert 'b'Rufiji'' to float

**Comment by pplonski** [comment] 2021-05-24 09:37
@ijeffking thank you for reporting. Could you please provide data and code to reproduce this issue. I've seen it before but couldn't reproduce the problem.

**Comment by ijeffking** [comment] 2021-05-24 09:47
Hello Piotr,

Here’s the link to download the Code

https://www.drivendata.org/competitions/7/pump-it-up-data-mining-the-water-table/data/

Here’s the Code…

automl = AutoML(
    mode="Optuna",
    algorithms=["CatBoost", "LightGBM", "Xgboost"],
    optuna_time_budget=800,
    total_time_limit=24*3600,
    golden_features=True,
    eval_metric="accuracy"
)

automl.fit(X_train, y_train)


2_Optuna_Xgboost accuracy 0.809068 trained in 545.93 seconds

[I 2021-05-23 15:32:49,079] A new study created in memory with name: no-name-8bea6d6c-f580-4185-8c1f-362ff9bae106

Optuna optimizes CatBoost with time budget 800 seconds eval_metric accuracy (maximize)

There was an error during 3_Optuna_CatBoost training.

Please check AutoML_2/errors.md for details.

Best,
Jeff


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by pplonski** [comment] 2021-05-24 09:58
@ijeffking thank you! Could you provide code for data loading? Just load training data CSV files? No other preprocessing?

**Comment by ijeffking** [comment] 2021-05-24 12:46
Hello Piotr,

Here’s what I have done….

df1 = pd.read_csv('/content/4910797b-ee55-40a7-8668-10efd5c1b960.csv')
df2 = pd.read_csv('/content/0bf8bc6e-30d0-4c50-956a-603fc693d966.csv')

df_merged = pd.merge(df1, df2, left_on=['id'],
              right_on=['id'],
              how='inner')

X = df_merged.drop("status_group", axis = 1)
y = df_merged.status_group

# Load the data
#housing = load_boston()
X_train, X_test, y_train, y_test = train_test_split(
    pd.DataFrame(X),
    y,
    test_size=0.25,
    random_state=123,
)

# training in Optuna mode, highly tune selected algorithm
automl = AutoML(
    mode="Optuna",
    algorithms=["CatBoost", "LightGBM", "Xgboost"],
    optuna_time_budget=800,
    total_time_limit=24*3600,
    golden_features=True,
    eval_metric="accuracy"
)

automl.fit(X_train, y_train)

That’s all. No preprocessing of any kind. FYI LGBM and XGB ran smoothly and produced good scores.

Best,
Jeff


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by pplonski** [comment] 2021-06-08 09:53
There was a problem with handling categoricals in CatBoost with Optuna mode. Should be fixed now. Changes are in the `master` branch. Install steps:

```
pip install -q -U git+https://github.com/mljar/mljar-supervised.git@master
```

**Closed by pplonski** 2021-06-08 09:53 UTC
Labels: bug

**Comment by pplonski** [comment] 2021-06-08 10:13
BTW @ijeffking in the provided example you are using `id` column as input, please remove this column from training for better results ;)
